name: test

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        uses: docker/bake-action@v5
        with:
          targets: test